language: emacs-lisp

sudo: required
dist: trusty

cache:
  - directories:
    - "$HOME/emacs"

matrix:
  fast_finish: true
  allow_failures:
    - env: EMACS_VERSION=snapshot

env:
  - EMACS_VERSION=25.1
  - EMACS_VERSION=25.2
  - EMACS_VERSION=25.3
  - EMACS_VERSION=26.1
  - EMACS_VERSION=snapshot

before_install:
  - export PATH="$HOME/bin:$PATH"
  - make setup
install:
  - make install

script:
  - make compile
  - make test

notifications:
  email:
    on_success: never
    on_failure: change
  webhooks:
    on_success: change
    on_failure: always
    on_start: never
